version: "3.7"
networks:
  app-tier:
    driver: bridge
services:
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.7.0
    restart: always
    networks:
      - app-tier
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9091,EXTERNAL://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  rabbitmq:
    container_name: rmq
    image: rabbitmq:3.12.0-alpine
    restart: always
    networks:
      - app-tier
    ports:
      - "5672:5672"
      - "15672:15672"





