name: Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'README_en.md'
      - '.github/**'
      - '.devcontainer/**'
      - 'LICENSE'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Run Test
        run:  gradle test
